// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/102er/apiserver/internal/server"
	"github.com/102er/apiserver/internal/service"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func initApi() (*gin.Engine, error) {
	userService := service.NewUserService()
	engine := server.NewGinHttpServer(userService)
	return engine, nil
}
